print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "M:/4th_Year/HonoursProject/Honours/Assets/TestScenes/Spider Scene/spoder.mb"`)
{		
	file -o "M:/4th_Year/HonoursProject/Honours/Assets/TestScenes/Spider Scene/spoder.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "M:/4th_Year/HonoursProject/Honours/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "M:/4th_Year/HonoursProject/Honours/Temp/CommandPipe";

$donepipeKill = `fopen "M:/4th_Year/HonoursProject/Honours/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
